### ISSUE TITLE
Do not use Rolling Update strategy on deployments for stateful apps

### ISSUE THREAD

**Issue by onedr0p** [TechSquidTV/UltimateHomeServer#24]
This will bring up a new pod before the old one is destroyed which can lead to data corruption on the persistence data with stateful applications.

Use a deployment strategy of Recreate instead, this will destroy the old pod before the new one starts.

Another option is to use statefulsets instead of deployments for stateful workloads.

**Comment by KyleTryon** [comment]
Thanks @onedr0p! I've checked out your repos and can see you've definitely got this all figured out 🙇. I can tell im going to be reading through your repos for a while.

**Comment by onedr0p** [comment]
> definitely got this all figured out
At the same time I feel like I have no idea what I am doing 😆

**Comment by onedr0p** [comment]
If you're interested check out this discord, lots of people doing the home k8s goodness. It could be a good place to bounce ideas off of.

https://discord.gg/k8s-at-home
