### ISSUE TITLE
Using nginx this way is a kubernetes anti-pattern

### ISSUE THREAD

**Issue by onedr0p** [TechSquidTV/UltimateHomeServer#26]
The proper was to get outside access to your cluster apps is to use an ingress controller like [ingress-nginx](https://github.com/kubernetes/ingress-nginx) and define ingress resources per application. For SSL the proper way to add certificates is to use [cert-manager](https://github.com/cert-manager/cert-manager). 

Once cert-manager is configured with the dns01 challenge you can put a common annotation on the ingresses to request, apply and use SSL certificates.

**Comment by aleksasiriski** [comment]
+1

**Comment by onedr0p** [comment]
Feel free to read my mission statement on the containers I build:

https://github.com/onedr0p/containers#mission-statement

**Comment by onedr0p** [comment]
Personally I would not use Traefik and instead use ingress-nginx.

See my comments here:
https://old.reddit.com/r/kubernetes/comments/137u79r/ingress_controller_for_vanilla_k8s/jiy8r89/

**Comment by aleksasiriski** [comment]
> @aleksasiriski I'm curious about the traefik recommendation - any particular reason to use it over nginx? Since most of the config is abstracted away by the ingress config anyways.

Personal preference, but go with either one. Some of the statements onedr0p mentions I can agree with but other not so much. So, again, it's personal preference for me but both are fine.

**Comment by onedr0p** [comment]
The author of this project is aware of this now and is up to them to wether or not to update their project, closing...
